name: run-unitest
description: 'compile cpu and run unitests'
inputs:
  use-gpu:
          description: '-DWITH_GPU=ON or -DWITH_GPU=OFF'
          required: true
          default: '-DWITH_GPU=OFF'
  use-test:
          description: 'run unitest or not'
          required: false
runs:
  using: 'docker'
  image: 'turbo_transformers:ci'
  args:
        - ${{inputs.use-gpu}}
        - '/workspace'
        - ${{inputs.use-test}}
